/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uidsystem;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author FLAVA FM PRODUCTION
 */
public class PASSPORT extends javax.swing.JFrame {

    /**
     * Creates new form PASSPORT
     */
    public PASSPORT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMenu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabelCLIENT = new javax.swing.JLabel();
        jLabelNRC = new javax.swing.JLabel();
        jLabelPASSPORT = new javax.swing.JLabel();
        jLabelDRIVER = new javax.swing.JLabel();
        jLabelLOGOUT = new javax.swing.JLabel();
        jLabelUSERREG = new javax.swing.JLabel();
        jLabelVOTER1 = new javax.swing.JLabel();
        jPanelHeader = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanelBody = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabelSearch = new javax.swing.JLabel();
        jTextFieldSearch = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabelFirstName = new javax.swing.JLabel();
        jLabelLastName = new javax.swing.JLabel();
        jTextFieldRegCC = new javax.swing.JTextField();
        jTextFieldPN = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jButtonSAVE = new javax.swing.JButton();
        jButtonDELETE = new javax.swing.JButton();
        jButtonUPDATE = new javax.swing.JButton();
        jButtonCLEAR = new javax.swing.JButton();
        jButtonPRINT = new javax.swing.JButton();
        jLabelClientID = new javax.swing.JLabel();
        jTextFieldCID = new javax.swing.JTextField();
        jLabelLastName1 = new javax.swing.JLabel();
        jLabelLastName2 = new javax.swing.JLabel();
        jLabelLastName3 = new javax.swing.JLabel();
        jLabelLastName4 = new javax.swing.JLabel();
        jTextFieldDI = new javax.swing.JTextField();
        jTextFieldNation = new javax.swing.JTextField();
        jTextFieldDE = new javax.swing.JTextField();
        jTextFieldHeight = new javax.swing.JTextField();
        jLabelLastName5 = new javax.swing.JLabel();
        jTextFieldOCC = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableNRC = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelMenu.setBackground(new java.awt.Color(255, 0, 204));
        jPanelMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel3.setFont(new java.awt.Font("Bangla MN", 1, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home 2.png"))); // NOI18N
        jLabel3.setText("Home");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabelCLIENT.setFont(new java.awt.Font("Bangla MN", 1, 18)); // NOI18N
        jLabelCLIENT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/client 2.png"))); // NOI18N
        jLabelCLIENT.setText("Client");
        jLabelCLIENT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCLIENTMouseClicked(evt);
            }
        });

        jLabelNRC.setFont(new java.awt.Font("Bangla MN", 1, 18)); // NOI18N
        jLabelNRC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/id.png"))); // NOI18N
        jLabelNRC.setText("National Registration Card");
        jLabelNRC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNRCMouseClicked(evt);
            }
        });

        jLabelPASSPORT.setFont(new java.awt.Font("Bangla MN", 1, 18)); // NOI18N
        jLabelPASSPORT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/passport.png"))); // NOI18N
        jLabelPASSPORT.setText("Passport");
        jLabelPASSPORT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelPASSPORT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPASSPORTMouseClicked(evt);
            }
        });

        jLabelDRIVER.setFont(new java.awt.Font("Bangla MN", 1, 18)); // NOI18N
        jLabelDRIVER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/drivers-licence.png"))); // NOI18N
        jLabelDRIVER.setText("Driver's License");
        jLabelDRIVER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDRIVERMouseClicked(evt);
            }
        });

        jLabelLOGOUT.setFont(new java.awt.Font("Bangla MN", 1, 18)); // NOI18N
        jLabelLOGOUT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sign-out.png"))); // NOI18N
        jLabelLOGOUT.setText("Log Out/ Sign Out");
        jLabelLOGOUT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLOGOUTMouseClicked(evt);
            }
        });

        jLabelUSERREG.setFont(new java.awt.Font("Al Bayan", 1, 18)); // NOI18N
        jLabelUSERREG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/register.png"))); // NOI18N
        jLabelUSERREG.setText("User Registion");
        jLabelUSERREG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUSERREGMouseClicked(evt);
            }
        });

        jLabelVOTER1.setFont(new java.awt.Font("Bangla MN", 1, 18)); // NOI18N
        jLabelVOTER1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/voters.png"))); // NOI18N
        jLabelVOTER1.setText("Voter's Card");
        jLabelVOTER1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVOTER1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabelCLIENT)
                    .addComponent(jLabelNRC)
                    .addComponent(jLabelUSERREG)
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelPASSPORT))
                    .addComponent(jLabelLOGOUT)
                    .addComponent(jLabelVOTER1)
                    .addComponent(jLabelDRIVER))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCLIENT)
                .addGap(18, 18, 18)
                .addComponent(jLabelNRC)
                .addGap(18, 18, 18)
                .addComponent(jLabelPASSPORT)
                .addGap(18, 18, 18)
                .addComponent(jLabelVOTER1)
                .addGap(28, 28, 28)
                .addComponent(jLabelDRIVER)
                .addGap(27, 27, 27)
                .addComponent(jLabelLOGOUT)
                .addGap(18, 18, 18)
                .addComponent(jLabelUSERREG)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelHeader.setBackground(new java.awt.Color(255, 0, 0));
        jPanelHeader.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/company logo.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("PT Sans", 1, 55)); // NOI18N
        jLabel1.setText("UNIQUE IDENTIFICATION SYSTEM");

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHeaderLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 951, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelBody.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBody.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Client ID:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Malgun Gothic Semilight", 1, 14), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N

        jLabelSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search 2.1.png"))); // NOI18N

        jTextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchActionPerformed(evt);
            }
        });
        jTextFieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSearchKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabelSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabelSearch, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Client Information:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Malgun Gothic Semilight", 1, 14), new java.awt.Color(51, 51, 255))); // NOI18N

        jLabelFirstName.setFont(new java.awt.Font("Eurostile", 1, 14)); // NOI18N
        jLabelFirstName.setText("Country Code:");

        jLabelLastName.setFont(new java.awt.Font("Eurostile", 1, 14)); // NOI18N
        jLabelLastName.setText("Passport Number:");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operations:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Malgun Gothic Semilight", 1, 14), new java.awt.Color(0, 0, 255))); // NOI18N

        jButtonSAVE.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jButtonSAVE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        jButtonSAVE.setText("Save");
        jButtonSAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSAVEActionPerformed(evt);
            }
        });

        jButtonDELETE.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jButtonDELETE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close 2.png"))); // NOI18N
        jButtonDELETE.setText("Delete");
        jButtonDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDELETEActionPerformed(evt);
            }
        });

        jButtonUPDATE.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jButtonUPDATE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update 2.png"))); // NOI18N
        jButtonUPDATE.setText("Update");
        jButtonUPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUPDATEActionPerformed(evt);
            }
        });

        jButtonCLEAR.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jButtonCLEAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.jpeg"))); // NOI18N
        jButtonCLEAR.setText("Clear");
        jButtonCLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCLEARActionPerformed(evt);
            }
        });

        jButtonPRINT.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jButtonPRINT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/printer 3.png"))); // NOI18N
        jButtonPRINT.setText("Print");
        jButtonPRINT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPRINTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCLEAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonUPDATE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDELETE, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(jButtonSAVE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPRINT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSAVE, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonDELETE)
                .addGap(18, 18, 18)
                .addComponent(jButtonUPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCLEAR)
                .addGap(18, 18, 18)
                .addComponent(jButtonPRINT)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelClientID.setFont(new java.awt.Font("Eurostile", 1, 14)); // NOI18N
        jLabelClientID.setText("Client ID: ");

        jLabelLastName1.setFont(new java.awt.Font("Eurostile", 1, 14)); // NOI18N
        jLabelLastName1.setText("Date of Issue :");

        jLabelLastName2.setFont(new java.awt.Font("Eurostile", 1, 14)); // NOI18N
        jLabelLastName2.setText("Height :");

        jLabelLastName3.setFont(new java.awt.Font("Eurostile", 1, 14)); // NOI18N
        jLabelLastName3.setText("Date of Expiry :");

        jLabelLastName4.setFont(new java.awt.Font("Eurostile", 1, 14)); // NOI18N
        jLabelLastName4.setText("Nationality :");

        jLabelLastName5.setFont(new java.awt.Font("Eurostile", 1, 14)); // NOI18N
        jLabelLastName5.setText("Occupation :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLastName4)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFirstName)
                            .addComponent(jLabelClientID)
                            .addComponent(jLabelLastName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldRegCC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(jTextFieldCID, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPN)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelLastName1)
                            .addComponent(jLabelLastName3)
                            .addComponent(jLabelLastName2)
                            .addComponent(jLabelLastName5))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNation, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(jTextFieldDI)
                            .addComponent(jTextFieldDE)
                            .addComponent(jTextFieldHeight)
                            .addComponent(jTextFieldOCC))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClientID)
                    .addComponent(jTextFieldCID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFirstName)
                    .addComponent(jTextFieldRegCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLastName1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLastName3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLastName4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLastName2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLastName5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldOCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "All Client's Information:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Malgun Gothic Semilight", 1, 14), new java.awt.Color(0, 0, 255))); // NOI18N

        jTableNRC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Client ID", "C. Code", "Passport No.", "D. of Issue", "D. of Expiry", "Nationality", "Height", "Occupation"
            }
        ));
        jTableNRC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableNRCMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableNRC);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelBodyLayout = new javax.swing.GroupLayout(jPanelBody);
        jPanelBody.setLayout(jPanelBodyLayout);
        jPanelBodyLayout.setHorizontalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBodyLayout.setVerticalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBodyLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.dispose();
        new Home().setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabelCLIENTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCLIENTMouseClicked
        // TODO add your handling code here:
        this.dispose();
        ClientInformation ci=new ClientInformation();
        ci.setVisible(true);
    }//GEN-LAST:event_jLabelCLIENTMouseClicked

    private void jLabelPASSPORTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPASSPORTMouseClicked
        // TODO add your handling code here:
        this.dispose();
        PASSPORT pid=new PASSPORT();
        pid.setVisible(true);
    }//GEN-LAST:event_jLabelPASSPORTMouseClicked

    private void jLabelDRIVERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDRIVERMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Driver dr=new Driver();
        dr.setVisible(true);
    }//GEN-LAST:event_jLabelDRIVERMouseClicked

    private void jLabelLOGOUTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLOGOUTMouseClicked
        // TODO add your handling code here:
        this.dispose();
        LOGIN lo=new LOGIN();
        lo.setVisible(true);
    }//GEN-LAST:event_jLabelLOGOUTMouseClicked

    private void jLabelUSERREGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUSERREGMouseClicked
        // TODO add your handling code here:
        this.dispose();
        UserReg UR=new UserReg();
        UR.setVisible(true);
    }//GEN-LAST:event_jLabelUSERREGMouseClicked

    private void jLabelVOTER1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVOTER1MouseClicked
        // TODO add your handling code here:
        this.dispose();
        Voter vc=new Voter();
        vc.setVisible(true);
    }//GEN-LAST:event_jLabelVOTER1MouseClicked

    private void jTextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchActionPerformed

    private void jTextFieldSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchKeyPressed
        // How to Search
        DefaultTableModel tbModel = (DefaultTableModel)jTableNRC.getModel();
        TableRowSorter<DefaultTableModel> tr=new TableRowSorter<DefaultTableModel>(tbModel);
        jTableNRC.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(jTextFieldSearch.getText().trim()));
    }//GEN-LAST:event_jTextFieldSearchKeyPressed

    private void jButtonSAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSAVEActionPerformed
        // TODO add your handling code here:
        if(jTextFieldRegCC.getText().equals("")||jTextFieldPN.getText().equals("")||jTextFieldDI.getText().equals("")||jTextFieldDE.getText().equals("")||jTextFieldNation.getText().equals("")||jTextFieldHeight.getText().equals("")){
            // code for left blank fields
            JOptionPane.showMessageDialog(this, "Please Enter All Data!");

        }else{
            // if all data is enter
            //store enter data into string array DATA
            String data[] = {jTextFieldRegCC.getText(), jTextFieldPN.getText(), jTextFieldDI.getText(), jTextFieldDE.getText(), jTextFieldNation.getText(), jTextFieldHeight.getText()};

            DefaultTableModel tbModel = (DefaultTableModel)jTableNRC.getModel();
            //add string array data
            tbModel.addRow(data);// row added
            //sucessfully added messge
            JOptionPane.showMessageDialog(this, "Add Data Successfully!");
            jTextFieldRegCC.setText("");
            jTextFieldDI.setText("");
            jTextFieldPN.setText(null);
            jTextFieldDE.setText("");
            jTextFieldNation.setText("");
            jTextFieldHeight.setText("");
    }//GEN-LAST:event_jButtonSAVEActionPerformed
    }
    private void jButtonDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDELETEActionPerformed
        // TODO add your handling code here:
        //Delete the information in table
        DefaultTableModel tbModel = (DefaultTableModel)jTableNRC.getModel();
        if(jTableNRC.getSelectedRow()==-1){
            if(jTableNRC.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "Table is Empty");
            }else{
                JOptionPane.showMessageDialog(this, "You must enter all");
            }
        }else{
            tbModel.removeRow(jTableNRC.getSelectedRow());
    }//GEN-LAST:event_jButtonDELETEActionPerformed
    }
    private void jButtonUPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUPDATEActionPerformed

        //Update the table
        DefaultTableModel tbModel = (DefaultTableModel)jTableNRC.getModel();
        if(jTableNRC.getSelectedRow()==-1){
            if(jTableNRC.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "Table is Empty");
            }else{
                JOptionPane.showMessageDialog(this, "You must enter all");
            }
        }else{
            tbModel.setValueAt(jTextFieldRegCC.getText(),jTableNRC.getSelectedRow(),0);
            tbModel.setValueAt(jTextFieldPN.getText(),jTableNRC.getSelectedRow(),1);
            tbModel.setValueAt(jTextFieldDI.getText(),jTableNRC.getSelectedRow(),2);
            tbModel.setValueAt(jTextFieldDE.getText(),jTableNRC.getSelectedRow(),3);
            tbModel.setValueAt(jTextFieldNation.getText(),jTableNRC.getSelectedRow(),4);
            tbModel.setValueAt(jTextFieldHeight.getText(),jTableNRC.getSelectedRow(),5);
    }//GEN-LAST:event_jButtonUPDATEActionPerformed
    }
    private void jButtonCLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCLEARActionPerformed
        // TODO add your handling code here:
        jTextFieldRegCC.setText("");
        jTextFieldHeight.setText("");
        jTextFieldDI.setText("");
        jTextFieldDE.setText("");
        jTextFieldPN.setText(null);
        jTextFieldNation.setText("");
        jTextFieldCID.setText("");
    }//GEN-LAST:event_jButtonCLEARActionPerformed

    private void jButtonPRINTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPRINTActionPerformed
        // TODO add your handling code here:
        MessageFormat header=new MessageFormat("Print Report");
        MessageFormat footer=new MessageFormat("Page(0,number,integer)");
        try{
            jTableNRC.print(JTable.PrintMode.NORMAL, header, footer);
        }catch(Exception e){
            System.out.println("Error Client Information Print Button");
    }//GEN-LAST:event_jButtonPRINTActionPerformed
    }
    private void jTableNRCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableNRCMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tbModel = (DefaultTableModel)jTableNRC.getModel();
        jTextFieldCID.setText(tbModel.getValueAt(jTableNRC.getSelectedRow(), 0).toString());
        jTextFieldRegCC.setText(tbModel.getValueAt(jTableNRC.getSelectedRow(), 1).toString());
        jTextFieldPN.setText(tbModel.getValueAt(jTableNRC.getSelectedRow(), 2).toString());
        jTextFieldDI.setText(tbModel.getValueAt(jTableNRC.getSelectedRow(), 3).toString());
        jTextFieldDE.setText(tbModel.getValueAt(jTableNRC.getSelectedRow(), 4).toString());
        jTextFieldNation.setText(tbModel.getValueAt(jTableNRC.getSelectedRow(), 5).toString());
        jTextFieldHeight.setText(tbModel.getValueAt(jTableNRC.getSelectedRow(), 6).toString());
    }//GEN-LAST:event_jTableNRCMouseClicked

    private void jLabelNRCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNRCMouseClicked
        // TODO add your handling code here:
        this.dispose();
        NRC nid=new NRC();
        nid.setVisible(true);   
    }//GEN-LAST:event_jLabelNRCMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PASSPORT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PASSPORT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PASSPORT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PASSPORT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PASSPORT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCLEAR;
    private javax.swing.JButton jButtonDELETE;
    private javax.swing.JButton jButtonPRINT;
    private javax.swing.JButton jButtonSAVE;
    private javax.swing.JButton jButtonUPDATE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCLIENT;
    private javax.swing.JLabel jLabelClientID;
    private javax.swing.JLabel jLabelDRIVER;
    private javax.swing.JLabel jLabelFirstName;
    private javax.swing.JLabel jLabelLOGOUT;
    private javax.swing.JLabel jLabelLastName;
    private javax.swing.JLabel jLabelLastName1;
    private javax.swing.JLabel jLabelLastName2;
    private javax.swing.JLabel jLabelLastName3;
    private javax.swing.JLabel jLabelLastName4;
    private javax.swing.JLabel jLabelLastName5;
    private javax.swing.JLabel jLabelNRC;
    private javax.swing.JLabel jLabelPASSPORT;
    private javax.swing.JLabel jLabelSearch;
    private javax.swing.JLabel jLabelUSERREG;
    private javax.swing.JLabel jLabelVOTER1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelBody;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableNRC;
    private javax.swing.JTextField jTextFieldCID;
    private javax.swing.JTextField jTextFieldDE;
    private javax.swing.JTextField jTextFieldDI;
    private javax.swing.JTextField jTextFieldHeight;
    private javax.swing.JTextField jTextFieldNation;
    private javax.swing.JTextField jTextFieldOCC;
    private javax.swing.JTextField jTextFieldPN;
    private javax.swing.JTextField jTextFieldRegCC;
    private javax.swing.JTextField jTextFieldSearch;
    // End of variables declaration//GEN-END:variables
}
