/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uidsystem;

import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FLAVA FM PRODUCTION
 */
public class UserReg extends javax.swing.JFrame {

    /**
     * Creates new form UserReg
     */
    public UserReg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHeader = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanelBody = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabelFirstName = new javax.swing.JLabel();
        jLabelLastName = new javax.swing.JLabel();
        jTextFieldRegLN = new javax.swing.JTextField();
        jTextFieldEA = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jButtonSAVE = new javax.swing.JButton();
        jButtonDELETE = new javax.swing.JButton();
        jButtonUPDATE = new javax.swing.JButton();
        jButtonCLEAR = new javax.swing.JButton();
        jButtonPRINT = new javax.swing.JButton();
        jLabelClientID = new javax.swing.JLabel();
        jTextFieldFN = new javax.swing.JTextField();
        jLabelLastName2 = new javax.swing.JLabel();
        jLabelLastName3 = new javax.swing.JLabel();
        jLabelLastName4 = new javax.swing.JLabel();
        jTextFieldP = new javax.swing.JTextField();
        jTextFieldUN = new javax.swing.JTextField();
        jTextFieldCP = new javax.swing.JTextField();
        jPanelMenu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabelCLIENT = new javax.swing.JLabel();
        jLabelNRC = new javax.swing.JLabel();
        jLabelPASSPORT = new javax.swing.JLabel();
        jLabelDRIVER = new javax.swing.JLabel();
        jLabelLOGOUT = new javax.swing.JLabel();
        jLabelUSERREG = new javax.swing.JLabel();
        jLabelVOTER1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelHeader.setBackground(new java.awt.Color(255, 0, 0));
        jPanelHeader.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/company logo.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("PT Sans", 1, 55)); // NOI18N
        jLabel1.setText("UNIQUE IDENTIFICATION SYSTEM");

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHeaderLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 951, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelBody.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBody.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Client Information:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Malgun Gothic Semilight", 1, 14), new java.awt.Color(51, 51, 255))); // NOI18N

        jLabelFirstName.setFont(new java.awt.Font("Eurostile", 1, 14)); // NOI18N
        jLabelFirstName.setText("Last Name:");

        jLabelLastName.setFont(new java.awt.Font("Eurostile", 1, 14)); // NOI18N
        jLabelLastName.setText("Email Address:");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operations:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Malgun Gothic Semilight", 1, 14), new java.awt.Color(0, 0, 255))); // NOI18N

        jButtonSAVE.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jButtonSAVE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        jButtonSAVE.setText("Save");
        jButtonSAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSAVEActionPerformed(evt);
            }
        });

        jButtonDELETE.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jButtonDELETE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close 2.png"))); // NOI18N
        jButtonDELETE.setText("Delete");
        jButtonDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDELETEActionPerformed(evt);
            }
        });

        jButtonUPDATE.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jButtonUPDATE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update 2.png"))); // NOI18N
        jButtonUPDATE.setText("Update");
        jButtonUPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUPDATEActionPerformed(evt);
            }
        });

        jButtonCLEAR.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jButtonCLEAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.jpeg"))); // NOI18N
        jButtonCLEAR.setText("Clear");
        jButtonCLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCLEARActionPerformed(evt);
            }
        });

        jButtonPRINT.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jButtonPRINT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/printer 3.png"))); // NOI18N
        jButtonPRINT.setText("Print");
        jButtonPRINT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPRINTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSAVE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDELETE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(jButtonUPDATE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCLEAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPRINT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSAVE, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonDELETE)
                .addGap(18, 18, 18)
                .addComponent(jButtonUPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCLEAR)
                .addGap(18, 18, 18)
                .addComponent(jButtonPRINT))
        );

        jLabelClientID.setFont(new java.awt.Font("Eurostile", 1, 14)); // NOI18N
        jLabelClientID.setText("First Name: ");

        jLabelLastName2.setFont(new java.awt.Font("Eurostile", 1, 14)); // NOI18N
        jLabelLastName2.setText("Confirm Password :");

        jLabelLastName3.setFont(new java.awt.Font("Eurostile", 1, 14)); // NOI18N
        jLabelLastName3.setText("User Name :");

        jLabelLastName4.setFont(new java.awt.Font("Eurostile", 1, 14)); // NOI18N
        jLabelLastName4.setText("Password :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabelLastName3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldUN, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFirstName)
                            .addComponent(jLabelClientID)
                            .addComponent(jLabelLastName)
                            .addComponent(jLabelLastName4)
                            .addComponent(jLabelLastName2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldRegLN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelClientID)
                            .addComponent(jTextFieldFN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFirstName)
                            .addComponent(jTextFieldRegLN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLastName3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldUN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLastName4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLastName2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelBodyLayout = new javax.swing.GroupLayout(jPanelBody);
        jPanelBody.setLayout(jPanelBodyLayout);
        jPanelBodyLayout.setHorizontalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelBodyLayout.setVerticalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelMenu.setBackground(new java.awt.Color(204, 255, 204));
        jPanelMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel3.setFont(new java.awt.Font("Bangla MN", 1, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home 2.png"))); // NOI18N
        jLabel3.setText("Home");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabelCLIENT.setFont(new java.awt.Font("Bangla MN", 1, 18)); // NOI18N
        jLabelCLIENT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/client 2.png"))); // NOI18N
        jLabelCLIENT.setText("Client");
        jLabelCLIENT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCLIENTMouseClicked(evt);
            }
        });

        jLabelNRC.setFont(new java.awt.Font("Bangla MN", 1, 18)); // NOI18N
        jLabelNRC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/id.png"))); // NOI18N
        jLabelNRC.setText("National Registration Card");
        jLabelNRC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNRCMouseClicked(evt);
            }
        });

        jLabelPASSPORT.setFont(new java.awt.Font("Bangla MN", 1, 18)); // NOI18N
        jLabelPASSPORT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/passport.png"))); // NOI18N
        jLabelPASSPORT.setText("Passport");
        jLabelPASSPORT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPASSPORTMouseClicked(evt);
            }
        });

        jLabelDRIVER.setFont(new java.awt.Font("Bangla MN", 1, 18)); // NOI18N
        jLabelDRIVER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/drivers-licence.png"))); // NOI18N
        jLabelDRIVER.setText("Driver's License");
        jLabelDRIVER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDRIVERMouseClicked(evt);
            }
        });

        jLabelLOGOUT.setFont(new java.awt.Font("Bangla MN", 1, 18)); // NOI18N
        jLabelLOGOUT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sign-out.png"))); // NOI18N
        jLabelLOGOUT.setText("Log Out/ Sign Out");
        jLabelLOGOUT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLOGOUTMouseClicked(evt);
            }
        });

        jLabelUSERREG.setFont(new java.awt.Font("Al Bayan", 1, 18)); // NOI18N
        jLabelUSERREG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/register.png"))); // NOI18N
        jLabelUSERREG.setText("User Registion");
        jLabelUSERREG.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelUSERREG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUSERREGMouseClicked(evt);
            }
        });

        jLabelVOTER1.setFont(new java.awt.Font("Bangla MN", 1, 18)); // NOI18N
        jLabelVOTER1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/voters.png"))); // NOI18N
        jLabelVOTER1.setText("Voter's Card");
        jLabelVOTER1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVOTER1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabelCLIENT)
                    .addComponent(jLabelNRC)
                    .addComponent(jLabelUSERREG)
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelPASSPORT))
                    .addComponent(jLabelLOGOUT)
                    .addComponent(jLabelVOTER1)
                    .addComponent(jLabelDRIVER))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCLIENT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelNRC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelPASSPORT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelVOTER1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelDRIVER)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelLOGOUT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelUSERREG)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 1181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSAVEActionPerformed
        // TODO add your handling code here:
        if(jTextFieldRegLN.getText().equals("")||jTextFieldEA.getText().equals("")||jTextFieldEA.getText().equals("")||jTextFieldUN.getText().equals("")||jTextFieldP.getText().equals("")||jTextFieldCP.getText().equals("")){
            // code for left blank fields
            JOptionPane.showMessageDialog(this, "Please Enter All Data!");

        }else{
            // if all data is enter
            //store enter data into string array DATA
            String data[] = {jTextFieldRegLN.getText(), jTextFieldEA.getText(), jTextFieldEA.getText(), jTextFieldUN.getText(), jTextFieldP.getText(), jTextFieldCP.getText()};

            
    }//GEN-LAST:event_jButtonSAVEActionPerformed
    }
    private void jButtonDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDELETEActionPerformed
        // TODO add your handling code here:
        //Delete the information in table
       
    }//GEN-LAST:event_jButtonDELETEActionPerformed

    private void jButtonUPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUPDATEActionPerformed

        
    }//GEN-LAST:event_jButtonUPDATEActionPerformed

    private void jButtonCLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCLEARActionPerformed
        // TODO add your handling code here:
        jTextFieldRegLN.setText("");
        jTextFieldCP.setText("");
        jTextFieldEA.setText("");
        jTextFieldUN.setText("");
        jTextFieldEA.setText(null);
        jTextFieldP.setText("");
        jTextFieldFN.setText("");
    }//GEN-LAST:event_jButtonCLEARActionPerformed

    private void jButtonPRINTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPRINTActionPerformed
        // TODO add your handling code here:
        MessageFormat header=new MessageFormat("Print Report");
        MessageFormat footer=new MessageFormat("Page(0,number,integer)");
        
    }//GEN-LAST:event_jButtonPRINTActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.dispose();
        new Home().setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabelCLIENTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCLIENTMouseClicked
        // TODO add your handling code here:
        this.dispose();
        ClientInformation ci=new ClientInformation();
        ci.setVisible(true);
    }//GEN-LAST:event_jLabelCLIENTMouseClicked

    private void jLabelNRCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNRCMouseClicked
        // TODO add your handling code here:
        this.dispose();
        NRC nid=new NRC();
        nid.setVisible(true);
    }//GEN-LAST:event_jLabelNRCMouseClicked

    private void jLabelPASSPORTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPASSPORTMouseClicked
        // TODO add your handling code here:
        this.dispose();
        PASSPORT pid=new PASSPORT();
        pid.setVisible(true);
    }//GEN-LAST:event_jLabelPASSPORTMouseClicked

    private void jLabelDRIVERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDRIVERMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabelDRIVERMouseClicked

    private void jLabelLOGOUTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLOGOUTMouseClicked
        // TODO add your handling code here:
        this.dispose();
        LOGIN lo=new LOGIN();
        lo.setVisible(true);
    }//GEN-LAST:event_jLabelLOGOUTMouseClicked

    private void jLabelUSERREGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUSERREGMouseClicked
        // TODO add your handling code here:
        this.dispose();
        UserReg UR=new UserReg();
        UR.setVisible(true);
    }//GEN-LAST:event_jLabelUSERREGMouseClicked

    private void jLabelVOTER1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVOTER1MouseClicked
        // TODO add your handling code here:
        this.dispose();
        Voter vc=new Voter();
        vc.setVisible(true);
    }//GEN-LAST:event_jLabelVOTER1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserReg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCLEAR;
    private javax.swing.JButton jButtonDELETE;
    private javax.swing.JButton jButtonPRINT;
    private javax.swing.JButton jButtonSAVE;
    private javax.swing.JButton jButtonUPDATE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCLIENT;
    private javax.swing.JLabel jLabelClientID;
    private javax.swing.JLabel jLabelDRIVER;
    private javax.swing.JLabel jLabelFirstName;
    private javax.swing.JLabel jLabelLOGOUT;
    private javax.swing.JLabel jLabelLastName;
    private javax.swing.JLabel jLabelLastName2;
    private javax.swing.JLabel jLabelLastName3;
    private javax.swing.JLabel jLabelLastName4;
    private javax.swing.JLabel jLabelNRC;
    private javax.swing.JLabel jLabelPASSPORT;
    private javax.swing.JLabel jLabelUSERREG;
    private javax.swing.JLabel jLabelVOTER1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelBody;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JTextField jTextFieldCP;
    private javax.swing.JTextField jTextFieldEA;
    private javax.swing.JTextField jTextFieldFN;
    private javax.swing.JTextField jTextFieldP;
    private javax.swing.JTextField jTextFieldRegLN;
    private javax.swing.JTextField jTextFieldUN;
    // End of variables declaration//GEN-END:variables
}
